# deploy dashboard to Azure Container Registry via bash script
name: deploy_via_bash

# run on push to any branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if branch = main, environment = prod, else environment = dev
    environment: ${{ ((github.head_ref || github.ref_name) == 'main') && 'prod' || 'dev' }}
    permissions:
      id-token: write
      contents: read
    # retrieve variables from environment secrets and variables
    env:
      # deployment variables
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      # blank variable to store the certificate content
      AZURE_CLIENT_CERT_NAME: "blank"
      AZURE_CLIENT_CERT: ${{ secrets.AZURE_CLIENT_CERT }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}  
      # App env variables
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      STREAMLIT_PASSWORD: ${{ secrets.STREAMLIT_PASSWORD }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run deploy.sh
        shell: bash
        run: |
          bash deployment/deploy.sh
      - name: clean up
        if: always()
        shell: bash
        run: |
          az logout
          rm ${{ vars.AZURE_CLIENT_CERT_NAME }}